/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Control.Gestion_Hotelera;
import Modelo.Hotel;
import javax.swing.JOptionPane;

/**
 *
 * @author Alonso
 */
public class Pantallita extends javax.swing.JFrame {

    /**
     * Creates new form Pantallita
     */
    public Pantallita() {
        initComponents();
    }
    Gestion_Hotelera gestion = Gestion_Hotelera.getInstance();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_Codigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbx_Tipo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txt_Precio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_FechaIn = new javax.swing.JTextField();
        txt_FechaRe = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_Cantidad = new javax.swing.JTextField();
        btn_Registrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablita = new javax.swing.JTable();
        btn_Mostrar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txt_Dinero = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Código");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 186, -1, -1));

        txt_Codigo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(txt_Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 183, 154, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tipo de habitación");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 247, -1, -1));

        cbx_Tipo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbx_Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de habitación", "Habitación normal", "Habitación lujosa" }));
        cbx_Tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_TipoActionPerformed(evt);
            }
        });
        jPanel1.add(cbx_Tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 244, 195, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Precio");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 300, -1, -1));

        txt_Precio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(txt_Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 297, 136, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha de Ingreso");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 350, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fecha de Retiro");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 399, -1, -1));

        txt_FechaIn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(txt_FechaIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 350, 183, -1));

        txt_FechaRe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(txt_FechaRe, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 396, 183, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cantidad de personas");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 247, -1, -1));

        txt_Cantidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(txt_Cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 244, 93, -1));

        btn_Registrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Registrar.setForeground(new java.awt.Color(0, 153, 204));
        btn_Registrar.setText("Registrar Habitación");
        btn_Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 428, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 60)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("HOTEL");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 30, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo azul.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 510));

        jTabbedPane1.addTab("Datos de registro", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablita.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tablita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Tipo de habitación", "Precio", "Fecha de ingreso", "Fecha de retiro", "Cantidad personas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablita);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 18, 740, 318));

        btn_Mostrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Mostrar.setForeground(new java.awt.Color(0, 153, 204));
        btn_Mostrar.setText("Mostrar registros de habitaciones");
        btn_Mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MostrarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 354, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Dinero recaudado");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 436, -1, -1));

        txt_Dinero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel2.add(txt_Dinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 433, 103, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo azul.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 510));

        jTabbedPane1.addTab("Tabla de registros", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegistrarActionPerformed
        // TODO add your handling code here:
        String codigo_habitacion = txt_Codigo.getText();
        String tipo_habitacion = cbx_Tipo.getSelectedItem().toString();
        double precio_habitacion = Double.parseDouble(txt_Precio.getText());
        String fecha_ingreso = txt_FechaIn.getText();
        String fecha_final = txt_FechaRe.getText();
        int cantidad_personas = Integer.parseInt(txt_Cantidad.getText());
        
        Hotel h = new Hotel(codigo_habitacion, tipo_habitacion, fecha_ingreso, fecha_final, cantidad_personas);
        h.setPrecio_habitacion(precio_habitacion);
        
        String mensaje = "Desea registrar esta habitación?";
        int opcion = JOptionPane.showConfirmDialog(this, mensaje, "Registro", JOptionPane.YES_NO_OPTION);
        if (opcion == 0){
            String mensaje_si = "Habitación registrada";
            gestion.agregar(h);
            JOptionPane.showMessageDialog(this, mensaje_si);
            cbx_Tipo.setSelectedIndex(0);
            txt_Precio.setText("");
            txt_FechaIn.setText("");
            txt_FechaRe.setText("");
            txt_Cantidad.setText("");
        }else{
            String mensaje_no = "No se registró.";
            JOptionPane.showMessageDialog(this, mensaje_no);
            cbx_Tipo.setSelectedIndex(0);
            txt_Precio.setText("");
            txt_FechaIn.setText("");
            txt_FechaRe.setText("");
            txt_Cantidad.setText("");
        }
        
    }//GEN-LAST:event_btn_RegistrarActionPerformed

    private void btn_MostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MostrarActionPerformed
        // TODO add your handling code here:
        gestion.mostrar_Datos(tablita);
        double suma_dinero = gestion.total_Dinero();
        txt_Dinero.setText("S/."+suma_dinero);
    }//GEN-LAST:event_btn_MostrarActionPerformed

    private void cbx_TipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_TipoActionPerformed
        // TODO add your handling code here:
        String tipo_habitacion = (String) cbx_Tipo.getSelectedItem().toString();
        double precio = gestion.precios(tipo_habitacion);
        txt_Precio.setText(String.valueOf(precio));
    }//GEN-LAST:event_cbx_TipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantallita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantallita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantallita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantallita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantallita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Mostrar;
    private javax.swing.JButton btn_Registrar;
    private javax.swing.JComboBox<String> cbx_Tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tablita;
    private javax.swing.JTextField txt_Cantidad;
    private javax.swing.JTextField txt_Codigo;
    private javax.swing.JTextField txt_Dinero;
    private javax.swing.JTextField txt_FechaIn;
    private javax.swing.JTextField txt_FechaRe;
    private javax.swing.JTextField txt_Precio;
    // End of variables declaration//GEN-END:variables
}
